<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Dapper" Version="2.1.86" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="publish_output\web.config" />
    <_ContentIncludedByDefault Remove="publish_output\appsettings.Development.json" />
    <_ContentIncludedByDefault Remove="publish_output\appsettings.json" />
    <_ContentIncludedByDefault Remove="publish_output\TicketApp.deps.json" />
    <_ContentIncludedByDefault Remove="publish_output\TicketApp.runtimeconfig.json" />
    <_ContentIncludedByDefault Remove="publish_output\TicketApp.staticwebassets.endpoints.json" />
  </ItemGroup>

</Project>
